### ISSUE TITLE
Caller-sensitive methods on Semeru JDK

### ISSUE THREAD

**Issue by leeN** [SAP/project-fontus#23]
When [running the system tests under the Semeru JDK, two tests are failing](https://github.com/SAP/project-fontus/actions/runs/8033275099/job/21969262098). Namely, *Using a lambda to create a proxy* and *Forwarding Argument to Main via Reflection*. Both rely on the CallerSensitive annotation, which seems to be unsupported in this JDK implementation.

```
Exception in thread "main" java.lang.UnsupportedOperationException: Caller-sensitive method called StackWalker.getCallerClass()
at java.base/java.lang.StackWalker.getCallerClass(StackWalker.java:198)
at com.sap.fontus.taintaware.unified.reflect.IASMethod.invoke(IASMethod.java:217)
at Main.main(Main.java:11)
at Main.main(Main.java)
```

**Comment by leeN** [comment]
Have disabled the system tests on Semeru JDK for now.
